Version 4
SymbolType CELL
RECTANGLE Normal 64 48 -64 -32
SYMATTR Value LM317_TRANS
SYMATTR Prefix X
SYMATTR Value2 LM317_TRANS
SYMATTR Description LM317 voltage regulator
SYMATTR ModelFile LM317_TRANS.LIB
PIN -64 0 LEFT 8
PINATTR PinName I
PINATTR SpiceOrder 1
PIN 0 48 BOTTOM 8
PINATTR PinName ADJ
PINATTR SpiceOrder 2
PIN 64 16 RIGHT 8
PINATTR PinName O
PINATTR SpiceOrder 3
PIN 64 -16 RIGHT 8
PINATTR PinName 1
PINATTR SpiceOrder 4
